version: '3.8'
x-postgres-common:
  &postgres-common
  image: postgres:14-alpine
  user: postgres
  restart: always
  healthcheck:
    test: 'pg_isready -U postgres --dbname=base_1'
    interval: 10s
    timeout: 5s
    retries: 5
networks:
  Bot_network:
    driver: bridge
services:
  db_image:
    <<: *postgres-common
    container_name: db_image
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: base_1
      POSTGRES_PASSWORD: Qq12345
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on
      -c listen_addresses='*'
    volumes:
      - ./db/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    networks:
      Bot_network:
  db_repl_image:
    <<: *postgres-common
    container_name: db_repl_image
    build:
      context: ./db_repl
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      PGUSER: replicator
      PGPASSWORD: Qq12345
    command: |
      bash -c "
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=db_image --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    networks:
      Bot_network:
    depends_on:
      - db_image
    container_name: bot_image_repl
  bot_image:
    container_name: bot_image_
    build:
      context: ./bot
      dockerfile: Dockerfile
    networks:
      Bot_network:
    depends_on:
      - db_image
      - db_repl_image
